[tools]
java = "temurin-17.0.20+8"

# for git hooks
hk = "1.56.0"
pkl = "0.32.1"

[env]
# explicitly use pkl CLI instead of pklr library because the latter does not support all language features needed
HK_PKL_BACKEND = "pkl"

[hooks]
enter = "mise x -- hk install --mise"
postinstall = "mise x -- hk install --mise"
